# Generated by Django 3.2.6 on 2021-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='confirmed_increase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='confirmed_patient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='dead',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='quarantine',
            field=models.IntegerField(),
        ),
    ]
