# Generated by Django 3.2.6 on 2021-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_covid', '0002_auto_20210817_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='confirmed_increase',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='confirmed_patient',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='dead',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='quarantine',
            field=models.CharField(max_length=128),
        ),
    ]
